### ISSUE TITLE
Toevoeging van koppeling properties in de constructor

### ISSUE THREAD

**Issue by d-ries** [marielLatellaBarros/contactApp#1]
@marielLatellaBarros : De constructor was aangemaakt maar had nog geen functionaliteit. De parameters in de constructor werden dus niet gekoppeld aan de properties van de contact klasse in contact.model.ts. Hierdoor werden er lege Contact objecten aangemaakt & leek het alsof de input binding niet werkte.

contact.model.ts
```
 constructor (
        name: string,
        email: string,
        phone: string,
        isFavorite: boolean,
        avatar: 'assets/avatar.png',) {
     //hier mist code

    }
```

aanpassen naar:
```
export class Contact {
    name: string;
    email: string;
    phone: string;
    isFavorite: boolean;
    avatar: string;

    constructor (
        name: string,
        email: string,
        phone: string,
        isFavorite: boolean,
        avatar: 'assets/avatar.png',) {
    }
}
```

**Comment by marielLatellaBarros** [comment]
aha! Check and fixed! Bedankt @d-ries !
